name: Hourly
run-name: Update resourcepacks and leaderboards

on:
  schedule:
    - cron: "1 */1 * * *"
  push:
    branches:
      main

jobs:
  Update:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 18.x
    
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Run update (browser)
        env:
          WEBHOOK_UPDATES: ${{ secrets.WEBHOOK_UPDATES }}
          WEBHOOK_ERRORS: ${{ secrets.WEBHOOK_ERRORS }}
        run: npm run browser
      
      - name: Run update (leaderboards)
        env:
          DISCORD_API_TOKEN: ${{ secrets.DISCORD_API_TOKEN }}
          WEBHOOK_DAILY: ${{ secrets.WEBHOOK_DAILY }}
          WEBHOOK_WEEKLY: ${{ secrets.WEBHOOK_WEEKLY }}
        run: |
          npm i discord.js
          npm run leaderboards

      - name: Push changes
        run: |
          ls
          git config --global user.email "${{ secrets.MAIL }}"
          git config --global user.name "Actions"
          git add resourcepacks.json
          git add ./leaderboards/dailylist.json
          git add ./leaderboards/weeklylist.json
          git commit --allow-empty -m "[auto update]"
          git push https://toarch7:${{ secrets.API_TOKEN_GITHUB }}@github.com/toarch7/ntm-browser
